refactor build flow, test check action

diff --git a/include/fpga/testbenches/Makefile b/include/fpga/testbenches/Makefile
--- a/include/fpga/testbenches/Makefile
+++ b/include/fpga/testbenches/Makefile
@@ -1,3 +1,5 @@
+# Use: sudo apt-get install ghdl gtkwave
+
 RTL_DIR = ..
 TB_DIR = .
 WAVES_DIR = waves
@@ -5,8 +7,19 @@ WORK_DIR = work
 
 GHDL_FLAGS = --std=08 -fsynopsys -fexplicit --workdir=$(WORK_DIR)
 
-# all testbenches ending in _tb.vhd
 TESTBENCHES = $(patsubst %_tb.vhd,%.sim,$(wildcard $(TB_DIR)/*_tb.vhd))
+
+define build_tb
+	TB=$*_tb; \
+	RTL=$*; \
+	mkdir -p $(WORK_DIR); \
+	ghdl -a $(GHDL_FLAGS) $(TB_DIR)/tb_utils_pkg.vhd; \
+	if [ -f $(RTL_DIR)/$$RTL.vhd ]; then \
+		ghdl -a $(GHDL_FLAGS) $(RTL_DIR)/$$RTL.vhd; \
+	fi; \
+	ghdl -a $(GHDL_FLAGS) $(TB_DIR)/$${TB}.vhd; \
+	ghdl -e $(GHDL_FLAGS) $${TB};
+endef
 
 .PHONY: all
 all: $(TESTBENCHES)
@@ -14,42 +27,32 @@ all: $(TESTBENCHES)
 
 # command line
 %.sim:
+	@rm -rf *.cf; \
+	rm -rf $(WORK_DIR)/*.cf
+	@$(build_tb)
 	@TB=$*_tb; \
-	RTL=$*; \
-	mkdir -p $(WORK_DIR); \
-	rm -rf *.cf; \
-	rm -rf $(WORK_DIR)/*.cf; \
-	ghdl -a $(GHDL_FLAGS) $(TB_DIR)/tb_utils_pkg.vhd; \
-	if [ -f $(RTL_DIR)/$$RTL.vhd ]; then \
-		ghdl -a $(GHDL_FLAGS) $(RTL_DIR)/$$RTL.vhd; \
-	fi; \
-	ghdl -a $(GHDL_FLAGS) $(TB_DIR)/$${TB}.vhd; \
-	ghdl -e $(GHDL_FLAGS) $${TB}; \
-	ghdl -r $(GHDL_FLAGS) $${TB}
+	ghdl -r $(GHDL_FLAGS) $${TB} 2>&1 | tee $(WORK_DIR)/$${TB}_output.log; \
+	if grep -q "FAIL:" $(WORK_DIR)/$${TB}_output.log; then \
+		echo "Testbench $${TB} failed! Check $(WORK_DIR)/$${TB}_output.log for details."; \
+		exit 1; \
+	fi
 
-# waveforms
+# waveforms (gtkwave)
 %.wav:
+	@rm -rf *.cf; \
+	rm -rf $(WORK_DIR)/*.cf
+	@$(build_tb)
 	@TB=$*_tb; \
-	RTL=$*; \
-	mkdir -p $(WORK_DIR); \
-	rm -rf *.cf; \
-	rm -rf $(WORK_DIR)/*.cf; \
-	ghdl -a $(GHDL_FLAGS) $(TB_DIR)/tb_utils_pkg.vhd; \
-	if [ -f $(RTL_DIR)/$$RTL.vhd ]; then \
-		ghdl -a $(GHDL_FLAGS) $(RTL_DIR)/$$RTL.vhd; \
-	fi; \
-	ghdl -a $(GHDL_FLAGS) $(TB_DIR)/$${TB}.vhd; \
-	ghdl -e $(GHDL_FLAGS) $${TB}; \
-	ghdl -r $(GHDL_FLAGS) $${TB} --vcd=$${TB}.vcd; \
+	ghdl -r $(GHDL_FLAGS) $${TB} --wave=$(WORK_DIR)/$${TB}.ghw; \
 	if [ -f $(WAVES_DIR)/$*.gtkw ]; then \
-		gtkwave -a $(WAVES_DIR)/$*.gtkw $${TB}.vcd & \
+		gtkwave -a $(WAVES_DIR)/$*.gtkw $(WORK_DIR)/$${TB}.ghw & \
 	else \
-		gtkwave $${TB}.vcd & \
+		gtkwave $(WORK_DIR)/$${TB}.ghw & \
 	fi
 
 .PHONY: clean
 clean:
-	rm -rf $(WORK_DIR) *.cf *.vcd *.ghw
+	rm -rf $(WORK_DIR) *.cf *.vcd *.ghw *.log
 
 .PHONY: help
 help:
